# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('PermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=40)),
                ('Login', models.CharField(max_length=20)),
                ('HashPassword', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('PhoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('UserPermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('PermissionID', models.IntegerField()),
            ],
        ),
    ]
