# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FullName',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='HashPassword',
            new_name='hashpassword',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='PhoneNumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='userid',
        ),
    ]
